name: godrink CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18, 1.19]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18, 1.19]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Build
      run: go build -v .

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.18, 1.19]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Test
      run: go test -v .
